<?php

return [
    //Employees table - roles
    'ADMIN_ROLE_VALUE' => 1,
    'MANAGER_ROLE_VALUE' => 2,
    'ENGINEER_ROLE_VALUE' => 3,

    //project role
    'PROJECT_ROLE_TEAM_LEAD' => 1,
    'PROJECT_ROLE_PROGRAMMER' => 2,
    'PROJECT_ROLE_QA' => 3,

    //Employee table - approved_status
    'APPROVED_STATUS_REJECTED' => 1,
    'APPROVED_STATUS_APPROVED' => 2,
    'APPROVED_STATUS_PENDING' => 3,
    'APPROVED_STATUS_PENDING_APPROVAL_FOR_UPDATE' => 4,

    //Employee table - position
    'POSITION_JR_RESEARCH_DEVELOPMENT_VALUE' => 1,
    'POSITION_ASSISTANT_RESEARCH_DEVELOPMENT_VALUE' => 2,
    'POSITION_SR_ASSISTANT_RESEARCH_DEVELOPMENT_VALUE' => 3,
    'POSITION_ASSOC_RESEARCH_DEVELOPMENT_VALUE' => 4,
    'POSITION_SR_ASSOC_RESEARCH_DEVELOPMENT_VALUE' => 5,
    'POSITION_SUPERVISOR_VALUE' => 6,
    'POSITION_ADVISER_VALUE' => 7,
    'POSITION_ASSSITANT_MANAGER_VALUE' => 8,
    'POSITION_MANAGER_VALUE' => 9,
    
    'POSITION_1_NAME' => 'Junior Research and Development',
    'POSITION_2_NAME' => 'Assistant Research and Development',
    'POSITION_3_NAME' => 'Senior Assistant Research and Development',
    'POSITION_4_NAME' => 'Associate Research and Development',
    'POSITION_5_NAME' => 'Senior Associate Research and Development',
    'POSITION_6_NAME' => 'Supervisor',
    'POSITION_7_NAME' => 'Adviser',
    'POSITION_8_NAME' => 'Assistant Manager',
    'POSITION_9_NAME' => 'Manager',

    //Employee Mail Type
    'MAIL_NEW_REGISTRATION_REQUEST' => 1,
    'MAIL_NEW_REGISTRATION_APPROVAL' => 2,
    'MAIL_NEW_REGISTRATION_REJECTION' => 3,
    'MAIL_EMPLOYEE_UPDATE_REQUEST' => 4,
    'MAIL_EMPLOYEE_UPDATE_APPROVAL' => 5,
    'MAIL_EMPLOYEE_UPDATE_REJECTION' => 6,
    'MAIL_EMPLOYEE_UPDATE_BY_MANAGER' => 7,
    'MAIL_EMPLOYEE_PROJECT_LINK_REQUEST' => 8,
    'MAIL_EMPLOYEE_LAPTOP_LINK_REQUEST' => 9,
    'MAIL_EMPLOYEE_PROJECT_LINK_BY_MANAGER' => 10,
    'MAIL_EMPLOYEE_LAPTOP_LINK_BY_MANAGER' => 11,
    'MAIL_NEW_SOFTWARE_REQUEST' => 12,
    'MAIL_NEW_SOFTWARE_APPROVAL' => 13,
    'MAIL_NEW_SOFTWARE_REJECTION' => 14,
    'MAIL_SOFTWARE_UPDATE_REQUEST' => 15,
    'MAIL_SOFTWARE_UPDATE_APPROVAL' => 16,
    'MAIL_SOFTWARE_UPDATE_REJECT' => 17,
    'MAIL_SOFTWARE_PROJECT_LINK_REQUEST' => 18,

    //software type
    'SOFTWARE_TYPE_PROD_TOOL_VALUE' => 1,
    'SOFTWARE_TYPE_MESSAGING_VALUE' => 2,
    'SOFTWARE_TYPE_BROWSER_VALUE' => 3,
    'SOFTWARE_TYPE_SYSTEM_UTIL_VALUE' => 4,
    'SOFTWARE_TYPE_PROJECT_SPECIFIC_VALUE' => 5,
    'SOFTWARE_TYPE_PHONE_DRIVERS_VALUE' => 6,

    //softwaretype name
    'SOFTWARE_TYPE_PROD_TOOL_NAME' => 'Productivity Tools',
    'SOFTWARE_TYPE_MESSAGING_NAME' => 'Messaging/Collaboration ',
    'SOFTWARE_TYPE_BROWSER_NAME' => 'Browser',
    'SOFTWARE_TYPE_SYSTEM_UTIL_NAME' => 'System Utilities',
    'SOFTWARE_TYPE_PROJECT_SPECIFIC_NAME' => 'Project Specific Softwares',
    'SOFTWARE_TYPE_PHONE_DRIVERS_NAME' => 'Phone Drivers',


];